import fs from "fs-extra";
import path from "node:path";
import * as cheerio from "cheerio";
import type { CloneResult } from "../types.js";

export async function convertToNext(result: CloneResult, outDir: string): Promise<void> {
  const stagingDir = path.resolve(result.outDir);
  const target = path.resolve(outDir);

  let staticRoot = stagingDir;
  let cleanupStatic = false;

  if (stagingDir === target) {
    staticRoot = path.join(path.dirname(target), `.site-clone-static-${Date.now()}`);
    await fs.move(stagingDir, staticRoot);
    cleanupStatic = true;
  }

  await fs.ensureDir(target);
  // Clear target except when it was just emptied by move
  if (stagingDir !== target) {
    await fs.emptyDir(target);
  }

  try {
    await scaffoldNextProject(target);

    // Preserve framework paths under public/ so /_next/* and /assets/* resolve
    for (const folder of ["assets", "_next", "static", "images", "fonts"]) {
      const src = path.join(staticRoot, folder);
      if (await fs.pathExists(src)) {
        await fs.copy(src, path.join(target, "public", folder));
      }
    }

    for (const page of result.pages) {
      const htmlAbs = path.join(staticRoot, page.relativeHtmlPath);
      if (!(await fs.pathExists(htmlAbs))) continue;
      const html = await fs.readFile(htmlAbs, "utf8");
      const routeDir = htmlPathToAppRoute(page.relativeHtmlPath);
      const appDir = path.join(target, "app", routeDir);
      await fs.ensureDir(appDir);

      const { bodyHtml, cssHrefs, scriptSrcs } = transformHtmlToPage(html);
      const pageSource = buildPageTsx({ bodyHtml, cssHrefs, scriptSrcs });
      await fs.writeFile(path.join(appDir, "page.tsx"), pageSource, "utf8");
    }

    await ensureRootLayout(target, result.pages[0]?.title || "Cloned Site");

    await fs.writeJson(
      path.join(target, "clone-manifest.json"),
      {
        ...result.manifest,
        framework: "next",
      },
      { spaces: 2 }
    );

    await fs.writeFile(
      path.join(target, "README.md"),
      [
        "# Cloned Next.js Site",
        "",
        "Generated by `site-clone`.",
        "",
        "## Run",
        "",
        "```bash",
        "npm install",
        "npm run dev",
        "```",
        "",
        "Open http://localhost:3000",
        "",
        "## Notes",
        "",
        "- Markup is embedded for fidelity from the static capture.",
        "- Complex client-side apps may need manual cleanup.",
        "- Forms/APIs still point at original backends unless rewritten.",
        "",
      ].join("\n"),
      "utf8"
    );
  } finally {
    if (cleanupStatic) {
      await fs.remove(staticRoot);
    }
  }
}

async function scaffoldNextProject(target: string): Promise<void> {
  await fs.ensureDir(target);
  await fs.writeJson(
    path.join(target, "package.json"),
    {
      name: "cloned-site",
      version: "1.0.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
      },
      dependencies: {
        next: "^15.2.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
      },
      devDependencies: {
        "@types/node": "^22.13.10",
        "@types/react": "^19.0.10",
        "@types/react-dom": "^19.0.4",
        typescript: "^5.8.2",
      },
    },
    { spaces: 2 }
  );

  await fs.writeJson(
    path.join(target, "tsconfig.json"),
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    { spaces: 2 }
  );

  await fs.writeFile(
    path.join(target, "next.config.mjs"),
    `/** @type {import('next').NextConfig} */\nconst nextConfig = {\n  reactStrictMode: true,\n};\n\nexport default nextConfig;\n`,
    "utf8"
  );

  await fs.writeFile(
    path.join(target, "next-env.d.ts"),
    '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n',
    "utf8"
  );

  await fs.ensureDir(path.join(target, "app"));
  await fs.writeFile(
    path.join(target, "app", "globals.css"),
    "/* Linked stylesheets from the cloned site are loaded in page components. */\nhtml, body { margin: 0; }\n",
    "utf8"
  );
}

async function ensureRootLayout(target: string, title: string): Promise<void> {
  const layoutPath = path.join(target, "app", "layout.tsx");
  const source = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(title)},
  description: "Cloned with site-clone",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
  await fs.writeFile(layoutPath, source, "utf8");
}

function htmlPathToAppRoute(htmlPath: string): string {
  const normalized = htmlPath.replace(/\\/g, "/");
  if (normalized === "index.html") return "";
  if (normalized.endsWith("/index.html")) {
    return normalized.slice(0, -"/index.html".length);
  }
  if (normalized.endsWith(".html")) {
    return normalized.slice(0, -".html".length);
  }
  return normalized;
}

function transformHtmlToPage(html: string): {
  bodyHtml: string;
  cssHrefs: string[];
  scriptSrcs: string[];
} {
  const $ = cheerio.load(html);

  const cssHrefs: string[] = [];
  $('link[rel="stylesheet"]').each((_, el) => {
    const href = $(el).attr("href");
    if (href) cssHrefs.push(toPublicPath(href));
  });

  // Also keep inline <style> blocks
  const inlineStyles: string[] = [];
  $("style").each((_, el) => {
    const css = $(el).html();
    if (css) inlineStyles.push(`<style>${css}</style>`);
  });

  const scriptSrcs: string[] = [];
  $("script[src]").each((_, el) => {
    const src = $(el).attr("src");
    if (src) scriptSrcs.push(toPublicPath(src));
  });

  let bodyHtml = `${inlineStyles.join("\n")}${$("body").html() || ""}`;
  // Body came from a static HTML file using relative ./assets paths — map to public/
  bodyHtml = bodyHtml
    .replace(/(?:\.\.\/)+assets\//g, "/assets/")
    .replace(/\.\/assets\//g, "/assets/")
    .replace(/(["'(])assets\//g, "$1/assets/");
  return { bodyHtml, cssHrefs, scriptSrcs };
}

function toPublicPath(href: string): string {
  const cleaned = href.replace(/\\/g, "/");
  const idx = cleaned.indexOf("assets/");
  if (idx >= 0) return `/${cleaned.slice(idx)}`;
  if (cleaned.startsWith("/")) return cleaned;
  return `/${cleaned.replace(/^\.\//, "")}`;
}

function buildPageTsx(args: {
  bodyHtml: string;
  cssHrefs: string[];
  scriptSrcs: string[];
}): string {
  const linkTags = args.cssHrefs
    .map((href) => `      <link rel="stylesheet" href={${JSON.stringify(href)}} />`)
    .join("\n");

  const scriptTags = args.scriptSrcs
    .map(
      (src) =>
        `      <Script src={${JSON.stringify(src)}} strategy="afterInteractive" />`
    )
    .join("\n");

  return `"use client";

import Script from "next/script";

const html = ${JSON.stringify(args.bodyHtml)};

export default function Page() {
  return (
    <>
${linkTags}
      <div dangerouslySetInnerHTML={{ __html: html }} />
${scriptTags}
    </>
  );
}
`;
}
